-- 快捷键设置
require('tools.keymaps')
-- 插件管理
require('tools.plugins')
-- 基础设置
require('tools.options')
-- 插件配置
require('plugins.nvim-treesitter')
require('plugins.nvim-tree')
require('plugins.lualine')
require('plugins.gitsigns')
require('plugins.indent-blank-line')
require('plugins.nvim-treesitter-context')
require('plugins.nvim-colorizer')
require('plugins.fterm')
require('plugins.lsp-signature')
require('plugins.nvim-autopair')
require('lsp.cmp')
require('plugins.lspinstaller')
require('plugins.lsp-color')
require('plugins.bufferline')
require('plugins.spellsitter')
require('plugins.dashboard')
require('plugins.wilder')
require('plugins.lsp-saga')
require('plugins.lazygit')
require('plugins.comment')
